version: "3.4"
services:
  aservicetaxi:    
    container_name: aservicetaxi
    build:      
      context: .
      dockerfile:  ./Dockerfile
    depends_on: [ mssql ]
    ports:
      - "5000:80"

  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "1qaz@WSX"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"